# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install-build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    working_directory: ~/angular-cli-circleci
    docker:
      - image: circleci/node:16-browsers
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: angular-build
          command: yarn ng -- build --prod --aot --no-progress
      - run:
          name: angular-test
          command: yarn test -- --single-run --no-progress
      - store_artifacts:
          path: test-results.xml
      - run:
          name: angular-lint
          command: yarn lint -- --formatters-dir ./tslint-formatters --format junit -o tslint.xml
      - store_artifacts:
          path: tslint.xml

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - install-build
